#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:47:07 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672782427195
maven-metadata-minecraftlibaries.xml.lastUpdated=1672782427090
maven-metadata-spigotpublic.xml.lastUpdated=1672782427198
maven-metadata-dmulloy2.xml.lastUpdated=1672782427227
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672782427385
