#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:18:15 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672777095735
maven-metadata-minecraftlibaries.xml.lastUpdated=1672777095663
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672777095740
maven-metadata-dmulloy2.xml.lastUpdated=1672777095757
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672777095916
maven-metadata-spigotpublic.xml.error=
