#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:07:23 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672776442932
maven-metadata-minecraftlibaries.xml.lastUpdated=1672776442870
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672776443010
maven-metadata-spigotmc-public.xml.lastUpdated=1672776443032
maven-metadata-dmulloy2.xml.lastUpdated=1672776442925
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-spigotmc-public.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672776443097
maven-metadata-spigotpublic.xml.error=
