#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:07:02 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672776422580
maven-metadata-minecraftlibaries.xml.lastUpdated=1672776291863
maven-metadata-spigotpublic.xml.lastUpdated=1672776291920
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotmc-public.xml.lastUpdated=1672776292126
maven-metadata-dmulloy2.xml.lastUpdated=1672776291955
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-spigotmc-public.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672776292195
maven-metadata-spigotpublic.xml.error=
