#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:47:15 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778835180
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778703984
maven-metadata-spigotpublic.xml.lastUpdated=1672778704012
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-dmulloy2.xml.lastUpdated=1672778704163
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778704313
maven-metadata-spigotpublic.xml.error=
