#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:51:41 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778970805
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778970812
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672779101386
maven-metadata-dmulloy2.xml.lastUpdated=1672778970971
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778971071
maven-metadata-spigotpublic.xml.error=
