#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:46:15 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672782375080
maven-metadata-minecraftlibaries.xml.lastUpdated=1672782374998
maven-metadata-spigotpublic.xml.lastUpdated=1672782375145
maven-metadata-dmulloy2.xml.lastUpdated=1672782375063
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672782375319
