#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:54:29 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672782869749
maven-metadata-minecraftlibaries.xml.lastUpdated=1672782739639
maven-metadata-spigotpublic.xml.lastUpdated=1672782739864
maven-metadata-dmulloy2.xml.lastUpdated=1672782739770
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672782739957
