#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:47:49 UTC 2023
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778868735
maven-metadata-minecraft-libraries.xml.lastUpdated=1672778868976
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1672778869066
maven-metadata-minecraft-libraries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778868979
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778868892
maven-metadata-spigotpublic.xml.lastUpdated=1672778868882
maven-metadata-dmulloy2.xml.lastUpdated=1672778868749
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-temp.xml.error=
