#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:09:45 UTC 2023
maven-metadata-minecraftlibaries.xml.lastUpdated=1672780184833
maven-metadata-minecraft-libraries.xml.lastUpdated=1672780185131
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1672780185311
maven-metadata-minecraft-libraries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.lastUpdated=1672780185131
maven-metadata-spigotsnapshots.xml.lastUpdated=1672780185090
maven-metadata-spigotpublic.xml.lastUpdated=1672780185132
maven-metadata-dmulloy2.xml.lastUpdated=1672780184914
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-temp.xml.error=
