#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 22:01:52 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672783182061
maven-metadata-minecraftlibaries.xml.lastUpdated=1672783181860
maven-metadata-spigotpublic.xml.lastUpdated=1672783312120
maven-metadata-dmulloy2.xml.lastUpdated=1672783181970
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672783182171
