#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:13:11 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672776791206
maven-metadata-minecraftlibaries.xml.lastUpdated=1672776660181
maven-metadata-spigotpublic.xml.lastUpdated=1672776660020
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-dmulloy2.xml.lastUpdated=1672776660210
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672776660224
maven-metadata-spigotpublic.xml.error=
