#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:49:34 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672782574843
maven-metadata-minecraftlibaries.xml.lastUpdated=1672782444431
maven-metadata-spigotpublic.xml.lastUpdated=1672782444591
maven-metadata-dmulloy2.xml.lastUpdated=1672782444502
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672782444714
