#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:44:33 UTC 2023
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778672710
maven-metadata-minecraft-libraries.xml.lastUpdated=1672778672854
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1672778673023
maven-metadata-minecraft-libraries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778672857
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778672840
maven-metadata-spigotpublic.xml.lastUpdated=1672778672844
maven-metadata-dmulloy2.xml.lastUpdated=1672778672718
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-temp.xml.error=
