#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 19:59:48 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672775988430
maven-metadata-minecraftlibaries.xml.lastUpdated=1672775858632
maven-metadata-spigotpublic.xml.lastUpdated=1672775858677
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-dmulloy2.xml.lastUpdated=1672775858902
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672775858914
maven-metadata-spigotpublic.xml.error=
