#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:07:22 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672776442342
maven-metadata-minecraftlibaries.xml.lastUpdated=1672776442331
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672776442428
maven-metadata-dmulloy2.xml.lastUpdated=1672776442506
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672776442625
maven-metadata-spigotpublic.xml.error=
