#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:02:20 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672776140112
maven-metadata-minecraftlibaries.xml.lastUpdated=1672776139999
maven-metadata-spigotpublic.xml.lastUpdated=1672776140111
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-dmulloy2.xml.lastUpdated=1672776140251
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672776140271
maven-metadata-spigotpublic.xml.error=
