#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:45:57 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672782228120
maven-metadata-minecraftlibaries.xml.lastUpdated=1672782227946
maven-metadata-spigotpublic.xml.lastUpdated=1672782357783
maven-metadata-dmulloy2.xml.lastUpdated=1672782228054
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672782228276
