#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:17:10 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672780629826
maven-metadata-minecraftlibaries.xml.lastUpdated=1672780629784
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672780629916
maven-metadata-spigotmc-public.xml.lastUpdated=1672780630055
maven-metadata-dmulloy2.xml.lastUpdated=1672780629952
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672780630016
