#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:40:28 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672782028103
maven-metadata-minecraftlibaries.xml.lastUpdated=1672782028067
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672782028243
maven-metadata-spigotmc-public.xml.lastUpdated=1672782028323
maven-metadata-dmulloy2.xml.lastUpdated=1672782028228
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672782028313
