#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:12:29 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672780349693
maven-metadata-minecraftlibaries.xml.lastUpdated=1672780349661
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672780349789
maven-metadata-dmulloy2.xml.lastUpdated=1672780349817
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1672780349961
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672780349917
