#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:48:58 UTC 2023
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778938143
maven-metadata-minecraft-libraries.xml.lastUpdated=1672778937293
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1672778937407
maven-metadata-minecraft-libraries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778937296
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778937205
maven-metadata-spigotpublic.xml.lastUpdated=1672778937178
maven-metadata-dmulloy2.xml.lastUpdated=1672778937046
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-temp.xml.error=
