#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:48:22 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778902191
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778902168
maven-metadata-spigotpublic.xml.lastUpdated=1672778902190
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-dmulloy2.xml.lastUpdated=1672778902359
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778902387
maven-metadata-spigotpublic.xml.error=
