#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:40:08 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672782008285
maven-metadata-minecraftlibaries.xml.lastUpdated=1672782008240
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672782008481
maven-metadata-spigotmc-public.xml.lastUpdated=1672782008566
maven-metadata-dmulloy2.xml.lastUpdated=1672782008403
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672782008496
