#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:21:47 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672780777417
maven-metadata-minecraftlibaries.xml.lastUpdated=1672780777475
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672780777585
maven-metadata-spigotmc-public.xml.lastUpdated=1672780907784
maven-metadata-dmulloy2.xml.lastUpdated=1672780777529
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672780777698
