#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:40:07 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672781878370
maven-metadata-minecraftlibaries.xml.lastUpdated=1672781878211
maven-metadata-spigotpublic.xml.lastUpdated=1672782007596
maven-metadata-dmulloy2.xml.lastUpdated=1672781878346
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672781878530
