#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 21:17:10 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672780630612
maven-metadata-minecraftlibaries.xml.lastUpdated=1672780630574
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672780630724
maven-metadata-spigotmc-public.xml.lastUpdated=1672780630815
maven-metadata-dmulloy2.xml.lastUpdated=1672780630764
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672780630815
