#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:44:32 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778671752
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778671948
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-spigotpublic.xml.lastUpdated=1672778671779
maven-metadata-dmulloy2.xml.lastUpdated=1672778671932
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778672047
maven-metadata-spigotpublic.xml.error=
