#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:47:16 UTC 2023
maven-metadata-minecraftlibaries.xml.lastUpdated=1672778836073
maven-metadata-minecraft-libraries.xml.lastUpdated=1672778836233
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1672778836566
maven-metadata-dmulloy2.xml.error=
maven-metadata-temp.xml.lastUpdated=1672778836233
maven-metadata-minecraft-libraries.xml.error=
maven-metadata-spigotsnapshots.xml.lastUpdated=1672778836229
maven-metadata-spigotpublic.xml.lastUpdated=1672778836232
maven-metadata-dmulloy2.xml.lastUpdated=1672778836091
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-temp.xml.error=
