#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jan 03 20:17:53 UTC 2023
maven-metadata-spigotsnapshots.xml.lastUpdated=1672777073844
maven-metadata-minecraftlibaries.xml.lastUpdated=1672776943054
maven-metadata-spigotpublic.xml.lastUpdated=1672776943026
maven-metadata-spigotsnapshots.xml.error=
maven-metadata-dmulloy2.xml.lastUpdated=1672776943168
maven-metadata-minecraftlibaries.xml.error=
maven-metadata-temp.xml.error=
maven-metadata-temp.xml.lastUpdated=1672776943344
maven-metadata-spigotpublic.xml.error=
